---
- name: Configure webserver with nginx
  hosts: webservers
  become: true

  tasks:
    - name: Ensure nginx is installed
      package:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure sites-available directory exists
      file:
        path: /etc/nginx/sites-available
        state: directory
        mode: '0755'
    
    - name: Ensure sites-enabled directory exists
      file:
        path: /etc/nginx/sites-enabled
        state: directory
        mode: '0755'

    - name: Copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
      notify: Restart nginx

    - name: Enable configuration
      file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link
      notify: Restart nginx

    - name: Copy index.html
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
...